-- page-section.lua
-- Pandoc Lua filter that injects Word section breaks for named page styles
--
-- Usage in QMD (use .section-* class prefix):
--   ::: {.section-landscape}
--   | Wide | Table | Here |
--   :::
--
--   ::: {.section-body page-break="true" line-numbers="continuous"}
--   :::
--
-- Attributes:
--   page-break="true"     Start section on new page (default: false)
--   line-numbers="page"   Line numbers restart each page
--   line-numbers="section" Line numbers restart each section
--   line-numbers="continuous" Line numbers never restart
--   line-numbers="false"  Disable line numbers for this section
--
-- CSS configuration (optional - attributes can override):
--   @page landscape {
--     size: letter landscape;
--     margin: 0.5in;
--   }
--   @page body {
--     --docstyle-line-numbers: every 1;
--     --docstyle-line-numbers-restart: page;
--   }
--
-- The filter reads named page rules from a JSON file generated by the pre-render
-- hook. If no @page rule exists for a section name, the filter falls back to
-- default page properties (allowing sections to work without explicit CSS).
--
-- Section breaks and Pandoc's docx writer
-- ----------------------------------------
-- Word's section model: sectPr defines properties for the section that ENDS at
-- that point. The document's final sectPr (in <w:body>) defines the last section.
-- Pandoc's docx writer always emits this final sectPr from the reference document.
--
-- This filter inserts mid-document sectPr elements to create section breaks. The
-- final section's properties (including line numbers) come from the reference
-- document, generated by generate-reference.R with settings from page-config.json.
--
-- IMPORTANT: Page breaks use an explicit <w:br w:type="page"/> paragraph followed
-- by a continuous sectPr, NOT the nextPage section type. The nextPage type alone
-- is unreliable when Pandoc's docx writer inserts bookmark elements around the
-- break. The explicit break + continuous sectPr pattern matches how Word itself
-- creates page breaks in natively-authored documents.
--
-- IMPORTANT: Do NOT insert an additional sectPr at document end (in the Pandoc()
-- function). For empty marker divs this creates three sections instead of two,
-- and Word silently drops the earlier page break. Line numbers for the final
-- section must be configured in the reference document, not via an extra sectPr.
--
-- Wrapping divs (non-empty) DO insert a closing sectPr after their content.
-- This creates three sections (before | wrapped content | after), which is the
-- correct structure for scoping line numbers to the wrapped content only.
--
-- Round-trip support
-- ------------------
-- Section divs are wrapped in ADDIN DOCSTYLE field codes for harvest round-trip.
-- The JSON payload preserves the class name, page-break, and line-numbers
-- attributes so they can be reconstructed during docx_to_qmd() harvest.

-- Load shared field code utilities
local fcu = require("field-code-utils")

-- Debug logging (set DOCSTYLE_DEBUG=1 to enable)
local DEBUG = os.getenv("DOCSTYLE_DEBUG") == "1"
local function debug(msg)
  if DEBUG then
    io.stderr:write("[page-section] " .. msg .. "\n")
  end
end

local FORMAT = "openxml"

-- Deep copy a table (for nested structures like line-numbers)
-- Prevents reference aliasing when multiple markers use the same named style
local function deep_copy(t)
  if type(t) ~= "table" then return t end
  local copy = {}
  for k, v in pairs(t) do
    copy[k] = deep_copy(v)
  end
  return copy
end

-- Page configuration from JSON
local page_config = nil
local default_page = nil
local final_section_style = nil  -- Track the last .section-* style for final sectPr
local current_section_props = nil  -- Track current section for correct sectPr emission

-- Unit conversion: CSS units to twips (1/20th of a point)
-- 1 inch = 1440 twips, 1 pt = 20 twips, 1 cm = 567 twips, 1 mm = 56.7 twips
local function css_to_twips(value)
  if not value then return nil end

  local num, unit = string.match(value, "^([%d%.]+)(%a+)$")
  if not num then
    -- Try just a number (assume inches)
    num = tonumber(value)
    if num then return math.floor(num * 1440) end
    return nil
  end

  num = tonumber(num)
  if not num then return nil end

  unit = string.lower(unit)
  if unit == "in" then
    return math.floor(num * 1440)
  elseif unit == "pt" then
    return math.floor(num * 20)
  elseif unit == "cm" then
    return math.floor(num * 567)
  elseif unit == "mm" then
    return math.floor(num * 56.7)
  elseif unit == "px" then
    -- CSS standard: 96px = 1in
    return math.floor(num * 15)
  end

  return nil
end

-- Get page dimensions in twips for a given size
local function get_page_size(size, orientation)
  -- Standard page sizes in twips (width x height in portrait)
  local sizes = {
    letter = { w = 12240, h = 15840 },  -- 8.5" x 11"
    a4 = { w = 11906, h = 16838 },      -- 210mm x 297mm
    legal = { w = 12240, h = 20160 }    -- 8.5" x 14"
  }

  local dims = sizes[size] or sizes.letter

  if orientation == "landscape" then
    return dims.h, dims.w  -- Swap width and height
  else
    return dims.w, dims.h
  end
end

-- Build Word section properties XML
local function build_sect_pr(page_props, sect_type)
  sect_type = sect_type or "nextPage"  -- nextPage, continuous, evenPage, oddPage

  local size = page_props.size or "letter"
  local orientation = page_props.orientation or "portrait"
  local margins = page_props.margins or {}

  local w, h = get_page_size(size, orientation)

  -- Default margins (1 inch = 1440 twips)
  local margin_top = css_to_twips(margins.top) or 1440
  local margin_bottom = css_to_twips(margins.bottom) or 1440
  local margin_left = css_to_twips(margins.left) or 1440
  local margin_right = css_to_twips(margins.right) or 1440
  local gutter = css_to_twips(margins.gutter) or 0

  -- Build the sectPr XML
  local xml_parts = {
    '<w:sectPr>'
  }

  -- Section type
  table.insert(xml_parts, '<w:type w:val="' .. sect_type .. '"/>')

  -- Page size with orientation
  local orient_attr = ""
  if orientation == "landscape" then
    orient_attr = ' w:orient="landscape"'
  end
  table.insert(xml_parts, string.format(
    '<w:pgSz w:w="%d" w:h="%d"%s/>',
    w, h, orient_attr
  ))

  -- Page margins
  table.insert(xml_parts, string.format(
    '<w:pgMar w:top="%d" w:right="%d" w:bottom="%d" w:left="%d" w:header="720" w:footer="720" w:gutter="%d"/>',
    margin_top, margin_right, margin_bottom, margin_left, gutter
  ))

  -- Line numbers if configured
  if page_props["line-numbers"] and page_props["line-numbers"].enabled then
    local ln = page_props["line-numbers"]
    local count_by = ln["count-by"] or 1
    local restart = ln.restart or "newPage"
    local distance = css_to_twips(ln.distance) or 360  -- Default 0.25in

    debug("  build_sect_pr: adding line numbers with restart=" .. tostring(restart))

    -- Map restart values to Word
    local restart_map = {
      page = "newPage",
      section = "newSection",
      continuous = "continuous"
    }
    restart = restart_map[restart] or "newPage"

    table.insert(xml_parts, string.format(
      '<w:lnNumType w:countBy="%d" w:restart="%s" w:distance="%d"/>',
      count_by, restart, distance
    ))
  else
    debug("  build_sect_pr: no line numbers (page_props['line-numbers']=" ..
          tostring(page_props["line-numbers"]) .. ")")
  end

  table.insert(xml_parts, '</w:sectPr>')

  return table.concat(xml_parts)
end

-- Build section break paragraphs as a list of XML strings.
-- Returns a table of XML strings, each to be emitted as a separate RawBlock.
--
-- IMPORTANT: Each XML string must be a separate RawBlock. When concatenated
-- into a single RawBlock, Pandoc's docx writer may not process the page break
-- correctly (the break is silently dropped). Separate RawBlocks match how
-- raw openxml blocks in markdown are processed.
--
-- For page breaks: Word reliably renders an explicit <w:br w:type="page"/>
-- followed by a continuous sectPr. The nextPage sect type alone is unreliable
-- in some contexts (e.g., when Pandoc bookmark elements surround the break).
-- This matches the pattern Word itself uses in natively-authored documents.
local function build_section_break_paras(page_props, sect_type)
  local sect_pr = build_sect_pr(page_props, "continuous")
  if sect_type == "nextPage" then
    -- Two separate paragraphs: page break + continuous sectPr
    return {
      '<w:p><w:r><w:br w:type="page"/></w:r></w:p>',
      '<w:p><w:pPr>' .. sect_pr .. '</w:pPr></w:p>'
    }
  else
    return {
      '<w:p><w:pPr>' .. sect_pr .. '</w:pPr></w:p>'
    }
  end
end

-- Read page configuration from JSON file (delegates to shared loader)
local function load_page_config()
  return fcu.load_page_config()
end

-- Read configuration from metadata
function Meta(meta)
  -- Try to load from JSON file first
  page_config = load_page_config()

  -- Also check metadata for inline config (for testing)
  if meta.docstyle and meta.docstyle.page then
    local page = meta.docstyle.page

    -- Parse metadata into page_config structure
    if not page_config then
      page_config = { named = {} }
    end

    -- Store default page settings
    default_page = {
      size = page.size and pandoc.utils.stringify(page.size) or "letter",
      orientation = page.orientation and pandoc.utils.stringify(page.orientation) or "portrait",
      margins = {}
    }

    if page.margins then
      for k, v in pairs(page.margins) do
        default_page.margins[k] = pandoc.utils.stringify(v)
      end
    end
  end

  -- Set default page from config if available
  if page_config and not default_page then
    default_page = {
      size = page_config.size or "letter",
      orientation = page_config.orientation or "portrait",
      margins = page_config.margins or {},
      ["line-numbers"] = page_config["line-numbers"]
    }
  end

  -- Ultimate fallback
  if not default_page then
    default_page = {
      size = "letter",
      orientation = "portrait",
      margins = { top = "1in", bottom = "1in", left = "1in", right = "1in" }
    }
  end

  current_section_props = deep_copy(default_page)

  debug("Default page: " .. (default_page.size or "letter") ..
        " " .. (default_page.orientation or "portrait"))

  if page_config and page_config.named then
    for name, _ in pairs(page_config.named) do
      debug("Named page style available: " .. name)
    end
  end

  return nil
end

-- Process Div elements looking for .section-* classes
--
-- Word Section Model:
-- - A section runs from one section break to the next (or document end)
-- - Section properties are defined by the sectPr that ENDS the section
-- - The document's final sectPr defines properties for the LAST section
--
-- Usage (empty div as marker - recommended):
--   ::: section-body
--   :::
--
--   # 1. Introduction
--   Content here is in the body section...
--
-- Usage (div wrapping content - also supported):
--   ::: {.section-body}
--   # 1. Introduction
--   Content here is in the body section...
--   :::
--
-- The section marker inserts a section break that ENDS the previous section.
-- Everything after the marker is in the NEW section until the next marker or document end.
--
-- Add page-break="true" to start the new section on a new page:
--   ::: {.section-body page-break="true"}
--   :::

function Div(div)
  -- Only process for docx output
  if FORMAT ~= "openxml" then
    return nil
  end

  -- Look for section-* classes
  local section_style = nil
  for _, class in ipairs(div.classes) do
    local name = string.match(class, "^section%-(.+)$")
    if name then
      section_style = name
      break
    end
  end

  -- Handle standalone page break: ::: {.page-break} :::
  -- Emits explicit <w:br type="page"/> that Pandoc passes through reliably.
  -- Use this instead of \newpage which Pandoc drops near headings/bookmarks.
  -- Harvest detects <w:br type="page"/> and restores ::: {.page-break} :::
  if not section_style then
    for _, class in ipairs(div.classes) do
      if class == "page-break" then
        debug("Found .page-break div")
        local blocks = {}
        table.insert(blocks, pandoc.RawBlock("openxml",
          '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'))
        -- Pass through any content inside the div
        for _, block in ipairs(div.content) do
          table.insert(blocks, block)
        end
        return blocks
      end
    end
    return nil
  end

  debug("Found .section-" .. section_style .. " div")

  -- Get the named page properties for the NEW section
  -- IMPORTANT: Use deep_copy to avoid aliasing issues when multiple markers
  -- use the same named style. Without copy, modifying new_section_props
  -- (e.g., setting line-numbers) would corrupt the shared config table.
  local new_section_props = nil
  if page_config and page_config.named and page_config.named[section_style] then
    new_section_props = deep_copy(page_config.named[section_style])
    debug("  Using @page " .. section_style .. " properties")
  else
    -- No named @page rule found - fall back to default with style-specific inference
    debug("  No @page " .. section_style .. " rule found, using defaults")

    if section_style == "landscape" then
      -- Landscape: swap orientation
      new_section_props = {
        size = default_page.size or "letter",
        orientation = "landscape",
        margins = default_page.margins or {}
      }
    else
      -- Other styles (body, appendix, etc.): inherit from default_page
      -- This allows sections to work even without explicit @page rules
      new_section_props = {
        size = default_page.size or "letter",
        orientation = default_page.orientation or "portrait",
        margins = default_page.margins or {},
        ["line-numbers"] = default_page["line-numbers"]
      }
    end
  end

  -- Line numbers: opt-in only via div attribute.
  -- Default is NO line numbers. The @page CSS config provides page geometry
  -- (size, margins, orientation) but line numbers require explicit opt-in:
  --   ::: {.section-body line-numbers="continuous"}
  -- This matches user expectation: "open it, start writing" = no line numbers.
  -- Supports: line-numbers="true", "false", "page", "section", "continuous"
  local ln_attr = div.attributes["line-numbers"]
  if ln_attr then
    ln_attr = pandoc.utils.stringify(ln_attr)
  end

  -- Clear any inherited line numbers from CSS config; only div attribute controls
  new_section_props["line-numbers"] = nil

  if ln_attr and ln_attr ~= "false" and ln_attr ~= "none" then
    if ln_attr == "true" or ln_attr == "page" then
      new_section_props["line-numbers"] = {
        enabled = true,
        ["count-by"] = 1,
        restart = "page"
      }
      debug("  Line numbers enabled (restart per page) via attribute")
    elseif ln_attr == "section" then
      new_section_props["line-numbers"] = {
        enabled = true,
        ["count-by"] = 1,
        restart = "section"
      }
      debug("  Line numbers enabled (restart per section) via attribute")
    elseif ln_attr == "continuous" then
      new_section_props["line-numbers"] = {
        enabled = true,
        ["count-by"] = 1,
        restart = "continuous"
      }
      debug("  Line numbers enabled (continuous) via attribute")
    end
  else
    debug("  Line numbers: off (default, no attribute)")
  end

  -- In Word, sectPr defines properties for the section that ENDS at that point.
  -- To start a new section:
  -- 1. Insert sectPr with PREVIOUS section's properties (ends the previous section)
  -- 2. Content after that sectPr is in the new section
  -- 3. New section's properties come from the NEXT sectPr (or document's final sectPr)

  -- Check for page-break attribute: ::: {.section-body page-break="true"}
  local sect_type = "continuous"
  if pandoc.utils.stringify(div.attributes["page-break"] or "") == "true" then
    sect_type = "nextPage"
    debug("  Using nextPage section break")
  end

  -- Build result blocks
  local blocks = {}

  -- For page breaks: emit the explicit <w:br type="page"/> BEFORE the field code
  -- and sectPr. This prevents the page break from being sandwiched between two
  -- consecutive sectPr elements (e.g., a closing sectPr from a previous wrapping
  -- div and this opening sectPr), which causes Word to silently drop the break.
  if sect_type == "nextPage" then
    table.insert(blocks, pandoc.RawBlock("openxml",
      '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'))
    debug("  Page break emitted before section break")
  end

  -- === R-FIRST ASSEMBLY (v2) ===
  -- Instead of emitting complex sectPr XML that Pandoc wraps in container
  -- paragraphs (causing the 3-line gap), emit a simple text marker that
  -- the R finisher will find and process.
  --
  -- The R finisher will:
  -- 1. Find this marker
  -- 2. Build sectPr using page-config.json
  -- 3. Attach sectPr to the PRECEDING paragraph
  -- 4. Delete the marker paragraph (eliminates the gap)

  -- Determine line-numbers for marker
  local ln_for_marker = "none"
  if ln_attr and ln_attr ~= "false" and ln_attr ~= "none" then
    ln_for_marker = ln_attr
  end

  -- Build text marker: DOCSTYLE_SECTION::{class}::{page-break}::{line-numbers}
  local marker_text = string.format("DOCSTYLE_SECTION::section-%s::%s::%s",
    section_style,
    sect_type == "nextPage" and "true" or "false",
    ln_for_marker
  )
  debug("  Emitting marker: " .. marker_text)

  -- Build attributes for field code
  local field_attrs = {}
  if sect_type == "nextPage" then
    field_attrs["page-break"] = true
  end
  if ln_attr and ln_attr ~= "false" and ln_attr ~= "none" then
    field_attrs["line-numbers"] = ln_attr
  end
  -- Pass through all remaining div attributes (footer-left, header-left,
  -- page-start, etc.) so the R finisher can read them from the JSON payload
  local skip_attrs = {["line-numbers"]=true, ["page-break"]=true, ["page-break-after"]=true}
  for k, v in pairs(div.attributes) do
    if not field_attrs[k] and not skip_attrs[k] then
      field_attrs[k] = pandoc.utils.stringify(v)
    end
  end

  -- Emit field code + marker in a SINGLE paragraph to prevent 3-line gap
  -- Uses build_section_marker_para which combines BEGIN/instrText/SEPARATE/marker/END
  table.insert(blocks, pandoc.RawBlock("openxml",
    fcu.build_section_marker_para("section-" .. section_style, field_attrs, marker_text)))

  -- For wrapping divs (non-empty): emit content, then closing marker.
  -- The opening marker already contains complete field code (BEGIN/SEPARATE/marker/END).
  -- For empty marker divs: field code is already complete, nothing more needed.
  if #div.content > 0 then
    -- Div content
    for _, block in ipairs(div.content) do
      table.insert(blocks, block)
    end

    -- Closing marker: R finisher will attach sectPr to last content paragraph
    local close_page_break = pandoc.utils.stringify(div.attributes["page-break-after"] or "") == "true"
    local close_marker = string.format("DOCSTYLE_SECTION_END::section-%s::%s::%s",
      section_style,
      close_page_break and "true" or "false",
      ln_for_marker
    )
    debug("  Emitting closing marker: " .. close_marker)

    -- Page break after content if requested
    if close_page_break then
      table.insert(blocks, pandoc.RawBlock("openxml",
        '<w:p><w:pPr><w:suppressLineNumbers/></w:pPr><w:r><w:br w:type="page"/></w:r></w:p>'))
    end

    -- Closing marker in single paragraph with field code wrapper
    -- Strip footer/header/page-start attributes from closing markers — the
    -- finisher reads these from opening markers only (via payload shift)
    local close_skip = {}
    for k, v in pairs(skip_attrs) do close_skip[k] = v end
    close_skip["footer-left"]=true; close_skip["footer-center"]=true; close_skip["footer-right"]=true
    close_skip["header-left"]=true; close_skip["header-center"]=true; close_skip["header-right"]=true
    close_skip["footer"]=true; close_skip["header"]=true
    close_skip["page-start"]=true
    local close_attrs = {}
    if close_page_break then
      close_attrs["page-break"] = true
    end
    if ln_attr and ln_attr ~= "false" and ln_attr ~= "none" then
      close_attrs["line-numbers"] = ln_attr
    end
    for k, v in pairs(div.attributes) do
      if not close_attrs[k] and not close_skip[k] then
        close_attrs[k] = pandoc.utils.stringify(v)
      end
    end
    table.insert(blocks, pandoc.RawBlock("openxml",
      fcu.build_section_marker_para("section-" .. section_style .. "-end", close_attrs, close_marker)))

    debug("Wrapping div: section '" .. section_style .. "' opened and closed")
  else
    -- Empty marker div: field code already complete in single paragraph
    debug("Empty marker: section '" .. section_style .. "' started")
  end

  return blocks
end

-- Check output format and apply final section style if needed
function Pandoc(doc)
  if FORMAT == "docx" or FORMAT == "openxml" then
    FORMAT = "openxml"
  end

  -- NOTE: We intentionally do NOT insert an extra sectPr here for line numbers.
  --
  -- Previously, this function inserted a sectPr paragraph at the end to apply
  -- line number properties to the final section. However, this creates THREE
  -- sections in the document:
  --   1. Mid-document sectPr (from Div()) - ends front matter
  --   2. Filter's final sectPr (from here) - ends body section
  --   3. Pandoc's body sectPr - ends document
  --
  -- This confuses Word's page break rendering - the explicit <w:br type="page"/>
  -- before sectPr #1 gets silently ignored.
  --
  -- Instead, line numbers should be configured in the reference document via
  -- generate-reference.R, which properly sets <w:lnNumType> in Pandoc's final
  -- body sectPr. This approach:
  --   - Keeps only 2 sections (front matter + body)
  --   - Page breaks work reliably
  --   - Line numbers still apply to body content
  --
  -- See: R/page_layout.R apply_line_numbers() function

  if final_section_style and FORMAT == "openxml" then
    debug("Final section style tracked: " .. (final_section_style["line-numbers"] and "with line numbers" or "no line numbers"))
    debug("Line numbers should be configured in reference doc, not via extra sectPr")
  end

  return nil
end

-- Consume stray ":::" paragraphs that appear when users add standalone :::
-- markers in QMD (which Pandoc parses as literal text, not fenced div closers).
-- This ensures users only need to mark section STARTS - no closing markers needed.
function Para(para)
  -- Only process for docx output
  if FORMAT ~= "openxml" then
    return nil
  end

  -- Check if paragraph contains only ":::" (possibly with whitespace)
  if #para.content == 1 and
     para.content[1].t == "Str" and
     para.content[1].text:match("^:::?$") then
    debug("Consuming stray ':::' paragraph")
    return {}  -- Remove the paragraph
  end

  return nil  -- Keep unchanged
end

-- Filter execution order:
-- 1. Meta - load configuration
-- 2. Div - process .page-* and .section-* divs
-- 3. Para - consume stray ::: paragraphs
-- 4. Pandoc - apply final section style if needed
return {
  { Meta = Meta },
  { Div = Div },
  { Para = Para },
  { Pandoc = Pandoc }
}
