--- strip-docstyle.lua
--- Lua filter for preprint-typst rendering from docstyle QMD sources.
--- Extracts body-level abstract to metadata and strips docstyle-specific
--- div wrappers so the same QMD renders cleanly via quarto-preprint.

--- Pass 1: Extract abstract and keywords from body to metadata
function Pandoc(doc)
  local dominated_blocks = doc.blocks
  local abstract_blocks = pandoc.List()
  local keyword_inlines = nil
  local in_abstract = false
  local in_keywords = false
  local abstract_start = nil
  local abstract_end = nil

  for i, block in ipairs(dominated_blocks) do
    if block.t == "Header" and block.level == 1 then
      if block.content and pandoc.utils.stringify(block.content) == "Abstract" then
        in_abstract = true
        in_keywords = false
        abstract_start = i
      elseif in_abstract then
        -- Hit the next level-1 heading: abstract section is over
        abstract_end = i - 1
        in_abstract = false
        in_keywords = false
        break
      end
    elseif in_abstract then
      if block.t == "Header" and block.level == 2 then
        local heading_text = pandoc.utils.stringify(block.content)
        if heading_text == "Keywords" then
          in_keywords = true
        else
          -- Convert abstract subsection headings to bold paragraphs
          in_keywords = false
          abstract_blocks:insert(pandoc.Para(
            {pandoc.Strong(block.content)}
          ))
        end
      elseif in_keywords then
        if block.t == "Para" then
          keyword_inlines = block.content
        end
      else
        abstract_blocks:insert(block)
      end
    end
  end

  -- If abstract_end wasn't set (abstract runs to end of doc), set it now
  if in_abstract and not abstract_end then
    abstract_end = #dominated_blocks
  end

  -- Move abstract to metadata and remove from body
  if abstract_start and abstract_end and #abstract_blocks > 0 then
    doc.meta.abstract = pandoc.MetaBlocks(abstract_blocks)

    if keyword_inlines then
      -- Split comma-separated keywords into a MetaList
      local kw_text = pandoc.utils.stringify(keyword_inlines)
      local keywords = pandoc.List()
      for kw in kw_text:gmatch("[^,]+") do
        local trimmed = kw:match("^%s*(.-)%.?%s*$")
        if trimmed and trimmed ~= "" then
          keywords:insert(pandoc.MetaInlines({pandoc.Str(trimmed)}))
        end
      end
      if #keywords > 0 then
        doc.meta.keywords = pandoc.MetaList(keywords)
      end
    end

    -- Remove abstract blocks from body (iterate in reverse to preserve indices)
    for i = abstract_end, abstract_start, -1 do
      dominated_blocks:remove(i)
    end
  end

  -- Insert a #refs div after the References heading so citeproc places the
  -- bibliography there instead of at the end of the document
  local new_blocks = pandoc.List()
  for i, block in ipairs(dominated_blocks) do
    new_blocks:insert(block)
    if block.t == "Header" and block.level == 1 then
      local text = pandoc.utils.stringify(block.content)
      if text:match("[Rr]eferences") then
        new_blocks:insert(pandoc.Div({}, pandoc.Attr("refs")))
      end
    end
  end

  doc.blocks = new_blocks
  return doc
end

--- Pass 2: Handle docstyle divs and date/version paragraphs

function Div(el)
  local classes = el.classes

  -- Page breaks → Typst pagebreak
  if classes:includes("page-break") then
    return pandoc.RawBlock("typst", "#pagebreak()")
  end

  -- Drop divs that are generated by docstyle Lua filters (empty in typst)
  if classes:includes("version-history") or
     classes:includes("author-plate") or
     classes:includes("toc") then
    return {}
  end

  -- Strip section wrapper divs, pass through content
  for _, cls in ipairs(classes) do
    if cls:match("^section%-") then
      return el.content
    end
  end

  return nil
end

function Para(el)
  local text = pandoc.utils.stringify(el)
  -- Drop date/version line: "2026-02-24 | Version: 0.2.5"
  if text:match("^%d%d%d%d%-%d%d%-%d%d%s*|%s*Version:") then
    return {}
  end
  return nil
end
